version: '3.9'

services:
  postgres-db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${MAIN_DB_PASSWORD}
      - POSTGRES_USER=${MAIN_DB_USER}
      - POSTGRES_DB=${MAIN_DB_NAME}

  todo-backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: todo-backend
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    depends_on:
      - postgres-db
    environment:
      DB_HOST: postgres-db
      DB_PORT: ${MAIN_DB_PORT}
      DB_NAME: ${MAIN_DB_NAME}
      DB_USER: ${MAIN_DB_USER}
      DB_PASSWORD: ${MAIN_DB_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
      FRONT_END_BASE_URL: ${FRONT_END_BASE_URL}
